#	$OpenBSD: src/sys/arch/sparc64/stand/ofwboot.net/Makefile,v 1.1 2001/08/18 16:31:53 jason Exp $

CPPFLAGS+=	-DNETBOOT
PROG=		ofwboot.net
.include "../ofwboot/Makefile"

.PATH: ${.CURDIR}/../ofwboot
