#	$OpenBSD: src/usr.sbin/pkg_install/lib/Attic/Makefile,v 1.4 1999/10/05 22:34:45 espie Exp $
LIB=	install
SRCS=	file.c plist.c str.c exec.c global.c pen.c
CFLAGS+= ${DEBUG}
NOPROFILE= yes
NOPIC=	yes

install:
	@echo -n

.include <bsd.lib.mk>
