# $OpenBSD: src/regress/lib/libpthread/socket/2/Makefile,v 1.1.1.1 2001/08/15 14:37:10 fgsch Exp $

PROG=	socket2
SRCS=	socket2.c
CFLAGS+= -I${.CURDIR}/../../include
CLEANFILES+= socket2a

.include <bsd.prog.mk>
