# $Id: Makefile,v 1.3 1996/03/18 05:45:55 jtk Exp $

SRCS=	apmd.c apmsubr.c
#LDADD+=	-lutil

CFLAGS+=	-g  -O2 -Wmissing-prototypes -Wall
PROG=	apmd
MAN=	apmd.8

.include <bsd.prog.mk>
# DO NOT DELETE THIS LINE -- make depend depends on it.
