#	$Id$

PROG=	pdisk

SRCS=	pdisk.c dump.c partition_map.c convert.c io.c errors.c bitfield.c \
	deblock_media.c file_media.c media.c pathname.c util.c validate.c

MAN=	pdisk.8

.include <bsd.prog.mk>
