#	$OpenBSD: src/usr.sbin/sendmail/mailstats/Attic/Makefile,v 1.1.1.2 1998/07/12 17:09:34 millert Exp $
#	@(#)Makefile	8.2 (Berkeley) 9/21/96

PROG=	mailstats
MAN=	mailstats.8
CFLAGS+=-I${.CURDIR}/../src

.include "../../Makefile.inc"
.include <bsd.prog.mk>
