#	$OpenBSD: src/sys/arch/hppa/stand/mkboot/Makefile,v 1.3 2000/05/31 19:52:59 mickey Exp $

PROG=	mkboot
CC=	${HOSTCC}
CFLAGS=-g -O
LDSTATIC=	-static
MAN=	mkboot.8
MANSUBDIR=/hppa

.include <bsd.prog.mk>
