#	$OpenBSD: src/distrib/sparc/ramdisk/Makefile.inc,v 1.2 1997/05/14 21:53:00 deraadt Exp $
#	$OpenBSD: src/distrib/sparc/ramdisk/Makefile.inc,v 1.2 1997/05/14 21:53:00 deraadt Exp $

IMAGESIZE=		4096
BOOT_INSTALLBOOT?=	/usr/mdec/bootxx
GZIP?=			gzip
GZIPFLAGS?=		-9v
GZIPEXT?=		.gz
