# $OpenBSD: src/regress/lib/libc_r/pthread_cond_timedwait/Attic/Makefile,v 1.1.1.1 2001/08/15 14:37:12 fgsch Exp $

PROG=	pthread_cond_timedwait
SRCS=	pthread_cond_timedwait.c

.include <bsd.prog.mk>
