#!/bin/sh
# $Id: elisp-comp,v 1.1.2.1 1996/11/19 14:51:42 niklas Exp $
# Trivial script to compile the Elisp files.
setpath=${TMPDIR-/tmp}/elc.$$
echo "(setq load-path (cons nil load-path))" > $setpath
emacs -batch -l $setpath -f batch-byte-compile "$@"
rm -f $setpath
