#!/bin/sh
# $OpenBSD: src/gnu/usr.bin/gas/testscripts/Attic/dounsortsymbols,v 1.2 1998/02/15 18:50:14 niklas Exp $
# objdump the symbol table, but strip off the headings and symbol
# numbers and sort the result.  Intended for use in comparing symbol
# tables that may not be in the same order.

objdump +symbols +omit-symbol-numbers $1 \
	| sort
#eof
