#	from: @(#)Makefile	5.1 (Berkeley) 6/5/90
#	$Id: Makefile,v 1.1.1.1 1995/10/18 08:43:09 deraadt Exp $

# libresolv no longer needs a special version of the resolver routines.
# The resolver is always in libc.
# However, an empty library must exist in case something tries to use it.

LIB=resolv

SRCS=nothing.c

.include <bsd.lib.mk>
