# $OpenBSD: src/regress/usr.bin/gzsig/Makefile,v 1.2 2005/05/29 08:54:59 djm Exp $
# $Id: Makefile,v 1.1.1.1 2005/05/28 01:58:12 marius Exp $

regress:
	@sh ${.CURDIR}/gzsig.sh ${.CURDIR}

.include <bsd.regress.mk>
