# $OpenBSD: src/regress/usr.bin/gzsig/Makefile,v 1.1.1.1 2005/05/28 01:58:12 marius Exp $
# $Id: Makefile,v  1.2 2005/04/01 16:47:32 dugsong Exp $

regress:
	@sh ${.CURDIR}/gzsig.sh

.include <bsd.regress.mk>