# $OpenBSD: src/regress/usr.bin/gzsig/Makefile,v 1.3 2005/05/31 14:15:41 art Exp $
# $Id: Makefile,v 1.2 2005/05/29 08:54:59 djm Exp $

do-regress:
	@sh ${.CURDIR}/gzsig.sh ${.CURDIR}

REGRESS_TARGETS=do-regress

.include <bsd.regress.mk>
