#	$OpenBSD: src/usr.sbin/sendmail/Attic/Makefile,v 1.1.1.2 1998/07/12 17:09:17 millert Exp $

SUBDIR= src smrsh mailstats makemap praliases cf/cf
.if make(install)
SUBDIR+= doc/intro doc/op cf
.endif

.include <bsd.subdir.mk>
