#	from: @(#)Makefile	5.6.1.2 (Berkeley) 5/8/91
#	$Id: Makefile.main,v 1.0 1994/05/29 21:01:48 moj Exp $

SUBDIR=	

passwd group hosts networks rpc services protocols: _SUBDIRUSE

.include <bsd.subdir.mk>
