#	$OpenBSD: src/usr.sbin/sendmail/praliases/Attic/Makefile,v 1.1.1.2 1998/07/12 17:13:55 millert Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/7/93

PROG=	praliases
CFLAGS+=-I${.CURDIR}/../src -DNEWDB
MAN=	praliases.1

.include "../../Makefile.inc"
.include <bsd.prog.mk>
