#	$OpenBSD: src/usr.sbin/sendmail/smrsh/Attic/Makefile,v 1.1.1.1 1998/07/12 17:09:43 millert Exp $
#	@(#)Makefile	8.1 (Berkeley) 7/2/95

PROG=	smrsh
MAN=	smrsh.8
CFLAGS+=-I${.CURDIR}/../src -DCMDDIR=\"/usr/libexec/sm.bin\"

.include "../../Makefile.inc"
.include <bsd.prog.mk>
