#	$OpenBSD: src/share/man/man4/man4.armish/Makefile,v 1.1 2006/06/06 00:01:49 drahn Exp $

# TODO: aupxa(eventually) cpu
MAN=	autoconf.4 intro.4 mem.4 

MLINKS+= mem.4 kmem.4
MANSUBDIR=armish

.include <bsd.prog.mk>
