
#	$Id: Makefile,v 1.3 1996/08/16 22:44:35 moj Exp $

PROG=	mopa.out
SRCS=	mopa.out.c file.c

CFLAGS+= -I${.CURDIR} -I${.CURDIR}/.. -I${.CURDIR}/../common
.PATH:	${.CURDIR}/../common

.include <bsd.prog.mk>
