#	$OpenBSD: src/share/man/man4/man4.powerpc/Attic/Makefile,v 1.1 1998/09/24 04:43:05 rahnds Exp $
#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91
#	Id: Makefile,v 1.4 1995/12/14 05:41:38 deraadt Exp $

MAN=	com.4 

MANSUBDIR=/powerpc

.include <bsd.prog.mk>
