#	$OpenBSD: src/sys/arch/i386/isa/pcvt/Util/pcvtdoc/Attic/Makefile,v 1.5 2000/05/25 21:54:52 deraadt Exp $

MAN4=		pcvt.${MAN4EXT}
MANSUBDIR=	/i386
MLINKS=		pcvt.${MAN4EXT} vt.${MAN4EXT}

.include <bsd.prog.mk>
