# 	from: @(#)Makefile	8.2 (Berkeley) 2/16/94
#	$Id: Makefile,v 1.7 1995/08/18 15:46:41 chopps Exp $

#MAN=	console.4 intro.4 le.4 mem.4
#MLINKS=	mem.4 kmem.4
MANSUBDIR=/mvme6k

.include <bsd.prog.mk>
