#	from: @(#)Makefile	5.6.1.2 (Berkeley) 5/8/91
#	$Id: Makefile,v 1.2 1995/11/01 16:56:03 deraadt Exp $

SUBDIR=	makedbm mknetid stdethers stdhosts ypinit ypserv yptest yppush ypxfr

.include <bsd.subdir.mk>
