#	$OpenBSD: src/distrib/cats/ramdisk/Attic/Makefile.inc,v 1.1 2004/02/01 05:15:48 drahn Exp $

CRUNCHGENOPTS= -E

#	$OpenBSD: src/distrib/cats/ramdisk/Attic/Makefile.inc,v 1.1 2004/02/01 05:15:48 drahn Exp $

CRUNCHGENOPTS= -E

#	$OpenBSD: src/distrib/cats/ramdisk/Attic/Makefile.inc,v 1.1 2004/02/01 05:15:48 drahn Exp $

CRUNCHGENOPTS= -E

